# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/main.go
  build:
    cmds:
      - go build -o ./build ./cmd/main.go 
  test-all:
    cmds:
      - go test -v ./...
  

